### ISSUE TITLE
Path to drush is broken

### ISSUE THREAD

**Issue by voila** [lyrasis/docker-islandora-frontend#1]
After I built the islandora image,  

/.composer/vendor/bin/drush
(https://github.com/lyrasis/docker-islandora-frontend/blob/master/Dockerfile#L34)

didn't point to drush. 
Instead I had to link to: /root/.composer/vendor/drush/drush/drush

**Comment by mark-cooper** [comment]
Better late than never? =)

https://github.com/lyrasis/docker-islandora-frontend/blob/master/Dockerfile#L75
